/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void  main(String arg[]) 
	{
		//1st edition
		//System.out.println("光復香港 時代革命");
		Library lib=new Library();
		if(lib.someLibraryMethod()) 
		{
			System.out.println("光復香港 時代革命");
		}
		
		
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
