/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void  main(String arg[]) 
	{
		System.out.println("光復香港 時代革命");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
